const MessageType = {
  EMAIL_INVITE_SEND: 50,
  EMAIL_INVITE_RECEIVER: 51,
  EMAIL_RESPONSE_FROM: 60,
  EMAIL_RESPONSE_TO: 61,
  EMAIL_SEND_TO: 62,
  EMAIL_SEND_FROM: 63,
  EMAIL_DELETE: 64,
};

export default MessageType;
